import os.path
from rake_nltk import Rake

#f = open("abstract.txt",'r')

#text = f.read()

text = "Phishing is the act of stealing personal information from the online users by impersonating as a statutory source in the cyberspace. Phishers often bait online users to visit their forged webpages to acquire users sensitive information. Most of the anti—phishing techniques today, endeavor to identify the legitimacy of the webpages the user visits and warn them with a phishing label when the webpage is a phish. But, these warnings generated by the anti—phishing tools are generic and does not provide any assistance for the users to safely navigate to the legitimate webpages. Any anti-phishing technique will be incomplete and incompetent without having a victimized domain identiﬁcation in place. The method proposed in this paper addresses this lacuna by automatically identifying the victimized domain (target domain) of every successfully distinguished phish webpage. This method initially identiﬁes the possible target domains of the webpage by analyzing the feign relationships which exist between the webpage and its associated domains through the in-degree link associations. Further. a novel Target Validation (TVD) algorithm is used to ensure the correctness of the identiﬁed target domain which in turn helps in reducing the false target predictions of the system. The legitimacy of the webpage is further conﬁrmed using the identiﬁed target domain. The experiment results show that this method is efﬁcient in protecting users from the online identity attacks and also in identifying victimized domain with over 99% accuracy."

s = ""

list = text.split('.')

phrases = ['in this paper','in this ','in this study','our research','this paper proposes','this novel','this paper','this paper aimed','we describe','this article',
'this article extends','this work examined','the present study','we present','the objective of this paper','we examine','this paper surveys','this paper conducted',
'this paper presents','we develop a novel approach','we develop','in this paper,we have proposed','this paper describe','in this domain']

selected = []
for line in list:
	for phrase in phrases:
		lower = line.lower()
		index = lower.find(phrase)
		if index != -1:

			selected.append(line)
for i in selected:
	s = s+i+". "
text = s


r=Rake()
r.extract_keywords_from_text(text)

list = (r.get_ranked_phrases())
astext = ""
for items in list:
	print(items)
	astext = astext + items +" "

f=open("key_list_tagged.txt", "w+")
f.write(astext)

f.close()

os.system('python3 "remove stopwords and tag.py"')

os.system('python3 "find pattern.py"')

